name: Lint Commit Message

on: 
- pull_request
- push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
       fetch-depth: 0

    - run: |
       pwd
       ls

    - uses: wagoid/commitlint-github-action@v6  
